# Generated by Django 3.2.19 on 2023-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCryptosList',
            fields=[
                ('id',
                 models.CharField(
                     max_length=100,
                     primary_key=True,
                     serialize=False)),
            ],
        ),
    ]
