# Generated by Django 3.2.19 on 2023-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0014_auto_20230615_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='sell_price_multiplier',
            field=models.FloatField(default=1.001),
        ),
    ]
