# Generated by Django 3.2.19 on 2023-10-01 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_backend', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True)),
                ('cryptocurrency', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api_backend.cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_amounts', models.ManyToManyField(
                    through='wallet.CryptoCollection', to='api_backend.CryptoCurrency')),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cryptocollection',
            name='wallet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptowallet'),
        ),
    ]
