# Generated by Django 3.2.19 on 2023-09-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0016_auto_20230831_2026'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='cryptocurrency',
        ),
        migrations.AddField(
            model_name='wallet',
            name='cryptocurrency',
            field=models.ManyToManyField(to='api_backend.CryptoCurrency'),
        ),
    ]
