# Generated by Django 3.2.19 on 2023-09-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0016_auto_20230831_2026'),
        ('wallet', '0002_auto_20230930_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='cryptocurrency',
        ),
        migrations.CreateModel(
            name='CryptoAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.cryptocurrency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='cryptocurrencies',
            field=models.ManyToManyField(through='wallet.CryptoAmount', to='api_backend.CryptoCurrency'),
        ),
    ]
