# Generated by Django 3.2.19 on 2023-10-01 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Bag',
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_backend.cryptocurrency')),
                ('shopping_bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_bag.bag')),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='holdings',
            field=models.ManyToManyField(through='shopping_bag.Holding', to='api_backend.CryptoCurrency'),
        ),
        migrations.AddField(
            model_name='bag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
