# Generated by Django 3.2.19 on 2023-09-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='portfolio',
            new_name='shopping_bag',
        ),
    ]
