# Generated by Django 3.2.19 on 2023-09-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0003_holding_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='user',
        ),
    ]
