# Generated by Django 3.2.19 on 2023-09-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0007_auto_20230929_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paid',
        ),
    ]
